# Generated by Django 2.2.6 on 2019-10-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191024_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='publish',
        ),
        migrations.AddField(
            model_name='posts',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
